// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: file_svc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataChunk     []byte                 `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_file_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_file_svc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

type UploadResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FileId             string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	TotalBytesReceived int32                  `protobuf:"varint,2,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_file_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_file_svc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadResponse) GetTotalBytesReceived() int32 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

var File_file_svc_proto protoreflect.FileDescriptor

const file_file_svc_proto_rawDesc = "" +
	"\n" +
	"\x0efile_svc.proto\x12\afilesvc\".\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"data_chunk\x18\x01 \x01(\fR\tdataChunk\"[\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x120\n" +
	"\x14total_bytes_received\x18\x02 \x01(\x05R\x12totalBytesReceived2N\n" +
	"\vFileService\x12?\n" +
	"\n" +
	"UploadFile\x12\x16.filesvc.UploadRequest\x1a\x17.filesvc.UploadResponse(\x01B\tZ\a./protob\x06proto3"

var (
	file_file_svc_proto_rawDescOnce sync.Once
	file_file_svc_proto_rawDescData []byte
)

func file_file_svc_proto_rawDescGZIP() []byte {
	file_file_svc_proto_rawDescOnce.Do(func() {
		file_file_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_svc_proto_rawDesc), len(file_file_svc_proto_rawDesc)))
	})
	return file_file_svc_proto_rawDescData
}

var file_file_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_svc_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: filesvc.UploadRequest
	(*UploadResponse)(nil), // 1: filesvc.UploadResponse
}
var file_file_svc_proto_depIdxs = []int32{
	0, // 0: filesvc.FileService.UploadFile:input_type -> filesvc.UploadRequest
	1, // 1: filesvc.FileService.UploadFile:output_type -> filesvc.UploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_svc_proto_init() }
func file_file_svc_proto_init() {
	if File_file_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_svc_proto_rawDesc), len(file_file_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_svc_proto_goTypes,
		DependencyIndexes: file_file_svc_proto_depIdxs,
		MessageInfos:      file_file_svc_proto_msgTypes,
	}.Build()
	File_file_svc_proto = out.File
	file_file_svc_proto_goTypes = nil
	file_file_svc_proto_depIdxs = nil
}
