name: Python Venv action
description: Testing venv caching for Python

runs:
  using: composite
  steps:
    - name: Install GNU tools for GitHub Actions
      shell: sh
      run: apk add --no-cache tar

    - name: Cache virtual environment
      id: cache-env
      uses: actions/cache@v5
      with:
        path: ${{ github.action_path }}/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles(format('{0}/requirements.txt', github.action_path)) }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: sh
      run: |
        python -m venv ${{ github.action_path }}/.venv
        source ${{ github.action_path }}/.venv/bin/activate
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run script
      shell: sg
      run: |
        source ${{ github.action_path }}/.venv/bin/activate
        python ${{ github.action_path }}/main.py
