name: Boot Azure VM
description: Start or stop Azure virtual machine
inputs:
  name:
    type: string
    required: true
    description: Virtual machine name
  subscription-id:
    type: string
    required: true
    description: Azure subscription ID
runs:
  using: node24
  main: dist/index.js
