apiVersion: webapp.alkalax.io/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-guestbook
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
