name: Workflow Queue Scan
description: Searches for required runners for workflows
inputs:
  github_token:
    required: true

runs:
  using: composite
  steps:
    - name: Install GNU tools
      shell: sh
      run: |
        if ! command -v tar &> /dev/null || tar --help 2>&1 | grep -q "BusyBox"; then
          echo "Valud GNU tar not found. Installing..."
          if command -v apk &> /dev/null; then
            apk add --no-cache tar
          elif command -v apt-get &> /dev/null; then
            apt-get install -y tar
          elif command -v dnf &> /dev/null; then
            dnf install -y tar
          elif command -v yum &> /dev/null; then
            yum install -y tar
          else
            echo "Unknown package manager. Could not install tar."
            exit 1
          fi
        else
          echo "Valid GNU tar is already installed."
        fi

    - name: Generate dependency hash
      id: generate-hash
      shell: sh
      run: |
        HASH=$(md5sum "${GITHUB_ACTION_PATH}/requirements.txt" | awk '{ print $1 }')
        echo "hash=${HASJ}" >> $GITHUB_OUTPUT

    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v5
      with:
        path: .venv
        key: workflow-scan-${{ steps.generate-hash.outputs.hash }}
        restore-keys: |
          workflow-scan-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: sh
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --no-cache-dir -r "${GITHUB_ACTION_PATH}/requirements.txt"

    - name: Run script
      shell: sh
      env: 
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        source .venv/bin/activate
        python "${GITHUB_ACTION_PATH}/main.py"
