name: Base

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: [self-hosted]
    #container:
    #  image: python:3.11-alpine3.22

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/python-action

      - uses: ./.github/actions/js-action
        with:
          who-to-greet: Milan
