name: Base

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        type: string
        description: Who to greet

jobs:
  test:
    runs-on: [self-hosted]
    #container:
    #  image: python:3.11-alpine3.22

    steps:
      - uses: actions/checkout@v5
      
      - uses: ./.github/actions/python-action

      - uses: ./.github/actions/js-action
        if: inputs.who-to-greet != '' 
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - uses: ./.github/actions/js-action
        if: inputs.who-to-greet == '' 
