name: Build Queue Scan

on:
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: [self-hosted]

    steps:

      - uses: ./.github/actions/workflow-queue-scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
