name: Build Queue Scan

on:
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: [self-hosted]
    container:
      image: python:3.12-alpine3.22 

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/workflow-queue-scan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
