name: Build Queue Scan

on:
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: [self-hosted]
    container:
      #image: python:3.12-alpine3.22 
      image: public.ecr.aws/docker/library/python:3.11.8-bullseye
      #image: public.ecr.aws/docker/library/python:3.11.14-alpine3.21

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/prepare-container-env
        id: prep-env

      - uses: ./.github/actions/workflow-queue-scan
        id: scan-queue
        with:
          github-token: ${{ secrets.WORKFLOW_SCAN_TOKEN }}
          distro-id: ${{ steps.prep-env.outputs.distro-id }}
          hash: ${{ steps.prep-env.outputs.hash }}
          labels: self-hosted

      - shell: sh
        run: |
          echo "Matching runners:"
          echo "${{ steps.scan-queue.outputs.runners }}"
